var:
  pipelineName: SignedPipelinesDocker
  gitProvider: harsh_github
  path: harshkumar1/SignedPipelines-Docker
  branches: main
  nodePool: awsnp
  artifactory: Artifactory
  repo: test-automation-docker-local
  imageName: b0000.jfrog-pipelines.com/test-automation-docker-local/signedpipelinesdocker
